### ISSUE TITLE
Address TODO or remove commented code

### ISSUE THREAD

**Issue by bh2smith** [gnosis/module-factory#2]
Before deployment, the TODO could be either done or at least remove the commented code (as this would appear on etherscan once deployed and verified - forever!)

https://github.com/gnosis/module-factory/blob/596a702c58596bde863fb66bb5cf2d496faa2a5a/contracts/ModuleProxyFactory.sol#L4-L11

It seems this issue is also directly related to the reason the coverage report skips these contracts. I now see that these contracts are meant to be imported from elsewhere. I would hope that we can make these imports work properly and remove the copied contracts from this project.

**Comment by bh2smith** [comment]
By the looks of things, the procedure to follow for getting these imports to work and remove the copied contract code would be as follows:

1 Publish each of these three repos as npm packages under @gnosis.pm namespace

2. Add them as dependencies in this project's package.json

**Comment by cbrzn** [comment]
This has been addressed so I will close this!
